config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :properties, shallow: true do
    resources :units
  end

  resources :units, shallow: true do
    resources :rent_payments, only: [:edit, :update, :index]
    resources :tenants
  end
  
  resources :sessions, only: [:new, :create, :destroy]

  post "property_owners", to: "property_owners#sign_in"

  root to: "properties#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :property_owner
  has_many :units
  has_one_attached :photo
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  has_many :properties

  has_secure_password
end

app/models/rent_payment.rb
class RentPayment < ApplicationRecord
 belongs_to :unit
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :unit
  has_rich_text :notes

  validates :lease_start_date, presence: true 
  validates :lease_end_date, presence: true

  validates :lease_end_date, comparison: { greater_than: :lease_start_date }

  def lease_months
    (self.lease_start_date..self.lease_end_date).map do |date|
      "#{Date::MONTHNAMES[date.mon]} - #{date.year}"
    end.uniq
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :property
  has_one :tenant
  has_many :rent_payments
  has_rich_text :notes
  monetize :monthly_rent_cents

  def days_until_rent
    date_time = DateTime.now
    date_time.end_of_month.day - date_time.day
  end

  def monthly_rent
    return 0 if self.monthly_rent_cents.nil?

    Money.new(self.monthly_rent_cents * 100).format
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= PropertyOwner.find_by(id: session[:user_id])
  end

  def authorize 
    return if current_user

    redirect_to sessions_new_path 
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = current_user.properties
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end

  def create
    # TODO: Current user should be property owner.
    # current_user.properties.create(property_params)
    @property_owner = PropertyOwner.last
    @property = @property_owner.properties.create(property_params)

    if @property.save
      redirect_to @property
    else
      Rails.logger.error('Unable to save user')
      render 'new'
    end
  end

  private

  def property_params
    params.require(:property).permit(
      :property_owner_id,
      :building_name,
      :address,
      :city,
      :state,
      :zipcode,
      :country,
      :photo,
      :notes
    )
  end
end

app/controllers/property_owners_controller.rb
class PropertyOwnersController < ApplicationController
end

app/controllers/rent_payments_controller.rb
class RentPaymentsController < ApplicationController
  def index 
    @unit = Unit.find(params[:unit_id])
    @rent_payments = @unit.rent_payments 
    @dashboard = RentDashboard.new(unit: @unit)
  end
  
  def edit
    @rent_payment = RentPayment.find(params[:id])
  end

  def update
    @rent_payment = RentPayment.find(params[:id])

    if @rent_payment.update(rent_payment_params)
      redirect_to @rent_payment.unit
    end
  end

  private

  def rent_payment_params
    params.require(:rent_payment).permit(:date_paid, :format)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def create
    user = PropertyOwner.find_by(email: params[:email])
    
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to properties_path, status: :see_other
    else
      redirect_to sessions_new_path,  notice: "Invalid email or password"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to sessions_new_path, status: :see_other, notice: 'Logged out!'
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = Tenant.all
  end

  def show
    @tenant = Tenant.find(params[:id])
  end

  def new
    @unit = Unit.find(params[:unit_id])
    @tenant = Tenant.new
  end

  def create
    @unit = Unit.find(params[:unit_id])
    @tenant = Tenant.new(tenant_params.merge(unit_id: @unit.id))

    respond_to do |format|
      if @tenant.save
        RentPaymentBuilder.new({lease_end_date: @tenant.lease_end_date,
                                lease_start_date: @tenant.lease_start_date,
                                unit: @unit}).run

        format.html { redirect_to @tenant }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("form", partial: "errors", locals: {tenant: @tenant})
        end
      end
    end
  end

  def edit
    @tenant = Tenant.find(params[:id])
  end

  def update
    @tenant = Tenant.find(params[:id])

    if @tenant.update(tenant_params)
      RentPaymentBuilder.new({ lease_end_date: @tenant.lease_end_date,
                               lease_start_date: @tenant.lease_start_date,
                               unit: @tenant.unit }).run

      redirect_to @tenant, notice: "Tenant was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy!

    redirect_to root_path
  end

  private

  def tenant_params
    params.require(:tenant).permit(
      :unit_id,
      :first_name,
      :last_name,
      :email,
      :phone_number,
      :lease_start_date,
      :lease_end_date,
      :notes
    )
  end
end

app/controllers/units_controller.rb
# UnitsController manages REST actions for units in the PMS

class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
    @dashboard = RentDashboard.new(unit: @unit)
  end

  def new
    @property = Property.find(params[:property_id])
    @unit = Unit.new
  end

  def create
    @property = Property.find(params[:property_id])
    @unit = @property.units.create(unit_params)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.prepend(:unit_list, partial: "properties/unit",
          locals: { unit: @unit })
      end

      format.html { redirect_to unit_url }
    end
  end

  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to @unit, notice: 'Unit was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy!

    redirect_to root_path
  end

  private

  def unit_params
    params.require(:unit).permit(
      :property_id,
      :apartment_name,
      :status,
      :day_rent_due,
      :monthly_rent_cents,
      :rooms,
      :notes
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/property_owners_helper.rb
module PropertyOwnersHelper
end

app/helpers/rent_payments_helper.rb
module RentPaymentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/_login.html.erb
<div class="py-6">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
    <h1 class="text-2xl font-semibold text-gray-900">
    </h1>
  </div>
  <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
    <!-- Replace with your content -->


        <div class="min-h-full flex flex-col justify-center py-12 sm:px-6 lg:px-8">
          <div class="sm:mx-auto sm:w-full sm:max-w-md">
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">Sign in to your account</h2>
          </div>

          <%= form_with url: session_index_path do |form| %>
            <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
              <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
                <form class="space-y-6" action="#" method="POST">
                  <div>
                    <label for="email" class="block text-sm font-medium text-gray-700"> Email address </label>
                    <div class="mt-1">
                      <%= form.text_field :email, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                    </div>
                  </div>

                  <div>
                    <label for="password" class="block text-sm font-medium text-gray-700"> Password </label>
                    <div class="mt-1">
                      <%= form.password_field :password, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
                    </div>
                  </div>

                  <div class="flex items-center justify-between">
                    <div class="flex items-center">
                      <input id="remember-me" name="remember-me" type="checkbox" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded">
                      <label for="remember-me" class="ml-2 block text-sm text-gray-900"> Remember me </label>
                    </div>

                  </div>
                  <%= form.submit 'Sign In', class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              </div>
                </form>

            </div>
        </div>
      <% end %>
  </div>

  <!-- /End replace -->
</div>
<div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/properties/_unit.html.erb
<tr>
  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><%= unit.apartment_name %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= unit.monthly_rent %></td>
  <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= unit.rooms %></td>
  <td class="whitespace-nowrap py-4 px-3">
    <% if unit.status == "vacant" %>
      <span class="inline-flex rounded-full bg-yellow-100 px-2 text-xs font-semibold leading-5 text-yellow-800">
        <%= unit.status %>
      </span>
    <% else %>
      <span class="inline-flex rounded-full bg-green-100 px-2 text-xs font-semibold leading-5 text-green-800">
        <%= unit.status %>
      </span>
    <% end %>
  </td>
  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 md:pr-0">
    <%= link_to "Show",unit_path(unit), class:"text-indigo-600 hover:text-indigo-900"%>
  </td>
</tr>

app/views/properties/index.html.erb
<div class="py-6">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 md:px-8">
    <!-- Replace with your content -->
    <div class="px-4 sm:px-6 lg:px-8">
      <div class="sm:flex sm:items-center">
        <div class="sm:flex-auto">
          <h1 class="text-xl font-semibold text-gray-900">My Properties</h1>
        </div>
        <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
          <%= link_to 'Add Property', new_property_path, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
        </div>
      </div>
      <div class="mt-8 flex flex-col">
        <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
            <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
              <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Address</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">State</th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Zipcode</th>
                    <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span class="sr-only">Show</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                  <% @properties.each do |property| %>
                    <tr>
                      <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm sm:pl-6">
                        <div class="flex items-center">
                          <div class="h-10 w-10 flex-shrink-0">
                            <% if property.photo.attached? %>
                              <%= image_tag url_for(property.photo), class: "h-10 w-10 rounded-full"%>
                            <% else %>
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 21v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21m0 0h4.5V3.545M12.75 21h7.5V10.75M2.25 21h1.5m18 0h-18M2.25 9l4.5-1.636M18.75 3l-1.5.545m0 6.205l3 1m1.5.5l-1.5-.5M6.75 7.364V3h-3v18m3-13.636l10.5-3.819" />
                              </svg>

                            <% end %>
                          </div>
                          <div class="ml-4">
                            <div class="font-medium text-gray-900"><%= property.building_name %></div>
                          </div>
                        </div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <div class="text-gray-900"><%= property.address %></div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                        <div class="text-gray-900"><%= property.state %></div>
                        <div class="text-gray-500"><%= property.city %></div>
                      </td>
                      <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= property.zipcode %></td>
                      <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                        <%= link_to 'Show', property, class: "text-indigo-600 hover:text-indigo-900" %>
                      </td>
                    </tr>
                  <% end %>
                  <!-- More people... -->
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- /End replace -->
  </div>
</div>

app/views/units/_rents.html.erb
<% if dashboard.current_rent %>
  <div class="px-4 sm:px-6 lg:px-8 py-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-xl font-semibold text-gray-900">Rent History</h1>
        <p class="mt-2 text-sm text-gray-700">Rent due date is the <%= unit.day_rent_due %> of every month</p>
      </div>
      <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <%= link_to "Rent History", unit_rent_payments_url(unit), class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
      </div>
    </div>
    <%= turbo_frame_tag(dom_id(dashboard.current_rent)) do %>
      <div class="mt-8 flex flex-col">
        <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
            <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
              <table class="min-w-full divide-y divide-gray-300">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                      <a href="#" class="group inline-flex">
                        Month
                        <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
                        <span class="invisible ml-2 flex-none rounded text-gray-400 group-hover:visible group-focus:visible">
                          <!-- Heroicon name: mini/chevron-down -->
                          <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                          </svg>
                        </span>
                      </a>
                    </th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      <a href="#" class="group inline-flex">
                        Date Paid
                        <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
                        <span class="ml-2 flex-none rounded bg-gray-200 text-gray-900 group-hover:bg-gray-300">
                          <!-- Heroicon name: mini/chevron-down -->
                          <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                          </svg>
                        </span>
                      </a>
                    </th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      <a href="#" class="group inline-flex">
                        Status 
                        <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
                        <span class="invisible ml-2 flex-none rounded text-gray-400 group-hover:visible group-focus:visible">
                          <!-- Heroicon name: mini/chevron-down -->
                          <svg class="invisible ml-2 h-5 w-5 flex-none rounded text-gray-400 group-hover:visible group-focus:visible" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                          </svg>
                        </span>
                      </a>
                    </th>
                    <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      <a href="#" class="group inline-flex">
                        Receipt
                        <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
                        <span class="invisible ml-2 flex-none rounded text-gray-400 group-hover:visible group-focus:visible">
                          <!-- Heroicon name: mini/chevron-down -->
                          <svg class="invisible ml-2 h-5 w-5 flex-none rounded text-gray-400 group-hover:visible group-focus:visible" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
                          </svg>
                        </span>
                      </a>
                    </th>
                    <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 bg-white">
                  <tr>
                    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= Date::MONTHNAMES[dashboard.current_rent.month.to_i] %></td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                      <% if dashboard.current_rent.date_paid %>
                        <%= dashboard.current_rent.date_paid.strftime("%B %e, %Y") %>
                      <% end %>
                    </td>
                    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                      <%= dashboard.status %>
                    </td>
                    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                      <% if dashboard.status == 'Rent Paid' %>
                        <%= link_to "Edit", edit_rent_payment_path(dashboard.current_rent), class: "text-indigo-600 hover:text-indigo-900" %>
                      <% else %>
                        <%= link_to "Record Payment", edit_rent_payment_path(dashboard.current_rent), class: "text-indigo-600 hover:text-indigo-900" %>
                      <% end %>
                    </td>
                  </tr>
                  <!-- More people... -->
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/units/_tenants.html.erb
<div class="px-4 sm:px-6 lg:px-6 py-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Tenants</h1>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
      <% if unit.tenant.blank? %>
        <%= link_to new_unit_tenant_path(unit), class:"inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
          </svg>
          Add Tenant
        <% end %>
      <% else %>
        <%= link_to edit_tenant_path(unit.tenant), class:"inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
          </svg>
          Edit Tenant
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mt-8 flex flex-col">
    <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <ul role="list" class="divide-y divide-gray-200">
            <% if unit.tenant %>
              <li>
                <%= link_to unit.tenant, class: "block hover:bg-gray-50" do %>
                  <div class="flex items-center px-4 py-4 sm:px-6">
                    <div class="min-w-0 flex-1 flex items-center">
                      <div class="min-w-0 flex-1 px-4 md:grid md:grid-cols-2 md:gap-4">
                        <div>
                          <p class="text-sm font-medium text-indigo-600 truncate"><%= unit.tenant.full_name %></p>
                          <p class="mt-2 flex items-center text-sm text-gray-500">
                            <!-- Heroicon name: solid/mail -->
                            <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                              <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
                              <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
                            </svg>
                            <span class="truncate"><%= unit.tenant.email %></span>
                          </p>
                        </div>
                      </div>
                    </div>
                    <div>
                      <!-- Heroicon name: solid/chevron-right -->
                      <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                      </svg>
                    </div>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>